"use client"

import {
  FileText,
  Globe,
  ShoppingCart,
  PenTool,
  Search,
  Boxes,
} from "lucide-react"

export const colorClasses: Record<string, any> = {
  purple: {
    bg: "bg-purple-500",
    text: "text-purple-600",
    border: "border-purple-300",
    hover: "hover:bg-purple-600",
    badgeBg: "bg-purple-50",
    badgeText: "text-purple-600",
    borderPopular: "#dab2ff",
  },
  blue: {
    bg: "bg-blue-500",
    text: "text-blue-600",
    border: "border-blue-300",
    hover: "hover:bg-blue-600",
    badgeBg: "bg-blue-50",
    badgeText: "text-blue-600",
    borderPopular: "#8ec5ff",
  },
  teal: {
    bg: "bg-teal-500",
    text: "text-teal-600",
    border: "border-teal-300",
    hover: "hover:bg-teal-600",
    badgeBg: "bg-teal-50",
    badgeText: "text-teal-600",
    borderPopular: "#46edd5",
  },
  orange: {
    bg: "bg-primary",
    text: "text-primary",
    border: "border-orange-300",
    hover: "hover:bg-primary/90",
    badgeBg: "bg-orange-50",
    badgeText: "text-primary",
    borderPopular: "#ffb86a",
  },
  indigo: {
    bg: "bg-indigo-500",
    text: "text-indigo-600",
    border: "border-indigo-300",
    hover: "hover:bg-indigo-600",
    badgeBg: "bg-indigo-50",
    badgeText: "text-indigo-600",
    borderPopular: "#a3b3ff",
  },
  emerald: {
    bg: "bg-emerald-500",
    text: "text-emerald-600",
    border: "border-emerald-300",
    hover: "hover:bg-emerald-600",
    badgeBg: "bg-emerald-50",
    badgeText: "text-emerald-600",
    borderPopular: "#5ee9b5",
  },
}

export const services = {
  landing: {
    name: "Landing Page",
    icon: FileText,
    color: "purple",
    packages: [
      {
        name: "Basic",
        price: "5.000.000đ",
        duration: "2-4 ngày",
        description: "Phù hợp cho chiến dịch ngắn hạn",
        features: [
          "1 trang landing page đơn giản",
          "Thiết kế responsive mobile",
          "Form liên hệ cơ bản",
          "Tối ưu tốc độ tải trang",
          "1 lần chỉnh sửa miễn phí",
        ],
      },
      {
        name: "Premium",
        price: "9.000.000đ",
        duration: "4-7 ngày",
        description: "Lựa chọn phổ biến nhất",
        popular: true,
        features: [
          "1 trang landing chuyên nghiệp",
          "Thiết kế UX/UI tùy chỉnh",
          "Form tích hợp Marketing tools",
          "Animation & hiệu ứng mượt mà",
          "SEO cơ bản",
          "2 lần chỉnh sửa miễn phí",
          "Hỗ trợ 30 ngày",
        ],
      },
      {
        name: "Professional",
        price: "15.000.000đ +",
        duration: "7-14 ngày",
        description: "Giải pháp toàn diện",
        features: [
          "Landing page cao cấp với A/B testing",
          "Thiết kế UX/UI độc quyền",
          "Tích hợp đầy đủ Marketing automation",
          "Analytics & tracking chuyên sâu",
          "SEO nâng cao",
          "Live chat & chatbot",
          "3 lần chỉnh sửa miễn phí",
          "Hỗ trợ 90 ngày",
        ],
      },
    ],
  },
  corporate: {
    name: "Website Doanh nghiệp",
    icon: Globe,
    color: "blue",
    packages: [
      {
        name: "Basic",
        price: "12.000.000đ",
        duration: "7-10 ngày",
        description: "Website giới thiệu cơ bản",
        features: [
          "5-7 trang nội dung",
          "Thiết kế responsive",
          "Form liên hệ",
          "Google Maps tích hợp",
          "Quản trị nội dung đơn giản",
          "1 lần đào tạo sử dụng",
        ],
      },
      {
        name: "Premium",
        price: "25.000.000đ",
        duration: "14-21 ngày",
        description: "Lựa chọn phổ biến nhất",
        popular: true,
        features: [
          "10-15 trang nội dung đầy đủ",
          "Thiết kế chuyên nghiệp",
          "Trang tin tức/blog",
          "Tích hợp email marketing",
          "SEO cơ bản",
          "Đa ngôn ngữ (2 ngôn ngữ)",
          "2 lần đào tạo sử dụng",
          "Hỗ trợ 60 ngày",
        ],
      },
      {
        name: "Professional",
        price: "45.000.000đ +",
        duration: "21-30 ngày",
        description: "Giải pháp doanh nghiệp lớn",
        features: [
          "Không giới hạn trang",
          "Thiết kế cao cấp theo thương hiệu",
          "Portal khách hàng/đối tác",
          "Tích hợp CRM",
          "SEO nâng cao toàn diện",
          "Đa ngôn ngữ (3+ ngôn ngữ)",
          "Bảo mật nâng cao",
          "3 lần đào tạo chuyên sâu",
          "Hỗ trợ 120 ngày",
        ],
      },
    ],
  },
  ecommerce: {
    name: "Website Bán hàng",
    icon: ShoppingCart,
    color: "teal",
    packages: [
      {
        name: "Basic",
        price: "18.000.000đ",
        duration: "10-14 ngày",
        description: "Bắt đầu bán hàng online",
        features: [
          "Tối đa 100 sản phẩm",
          "Giỏ hàng & thanh toán cơ bản",
          "Tích hợp 1 cổng thanh toán",
          "Quản lý đơn hàng đơn giản",
          "Responsive mobile",
          "SEO sản phẩm cơ bản",
        ],
      },
      {
        name: "Premium",
        price: "35.000.000đ",
        duration: "21-28 ngày",
        description: "Lựa chọn phổ biến nhất",
        popular: true,
        features: [
          "Không giới hạn sản phẩm",
          "Đa phương thức thanh toán",
          "Tích hợp vận chuyển",
          "Quản lý kho hàng",
          "Mã giảm giá & khuyến mãi",
          "SEO toàn diện",
          "Email marketing tự động",
          "Báo cáo doanh số chi tiết",
          "Hỗ trợ 90 ngày",
        ],
      },
      {
        name: "Professional",
        price: "65.000.000đ +",
        duration: "30-45 ngày",
        description: "Nền tảng thương mại điện tử",
        features: [
          "Tất cả tính năng Premium",
          "Multi-vendor marketplace",
          "Tích hợp ERP/CRM",
          "AI recommendation engine",
          "Loyalty program",
          // "Mobile app đồng bộ",
          "Bảo mật cao cấp",
          "API cho tích hợp mở rộng",
          "Đào tạo team chuyên sâu",
          "Hỗ trợ 180 ngày",
        ],
      },
    ],
  },
  custom: {
    name: "Thiết kế theo yêu cầu",
    icon: PenTool,
    color: "orange",
    packages: [
      {
        name: "Basic",
        price: "20.000.000đ",
        duration: "14-21 ngày",
        description: "Giải pháp tùy chỉnh cơ bản",
        features: [
          "Phân tích yêu cầu chi tiết",
          "Thiết kế UI/UX riêng biệt",
          "Tính năng cơ bản theo yêu cầu",
          "Responsive đa thiết bị",
          "Testing & debug",
          "Tài liệu kỹ thuật",
        ],
      },
      {
        name: "Premium",
        price: "45.000.000đ",
        duration: "30-45 ngày",
        description: "Lựa chọn phổ biến nhất",
        popular: true,
        features: [
          "Tư vấn giải pháp chuyên sâu",
          "Thiết kế UX/UI cao cấp",
          "Tính năng phức tạp tùy chỉnh",
          "Tích hợp hệ thống bên thứ 3",
          "Admin panel quản trị",
          "API development",
          "Testing toàn diện",
          "Đào tạo sử dụng",
          "Hỗ trợ 90 ngày",
        ],
      },
      {
        name: "Professional",
        price: "100.000.000đ +",
        duration: "60+ ngày",
        description: "Nền tảng enterprise",
        features: [
          "Tư vấn kiến trúc hệ thống",
          "Full-stack development",
          "Microservices architecture",
          "Cloud infrastructure",
          "Bảo mật cấp enterprise",
          "CI/CD pipeline",
          "Performance optimization",
          "Load balancing & scaling",
          "24/7 monitoring",
          "Hỗ trợ 365 ngày",
        ],
      },
    ],
  },
  marketing: {
    name: "Marketing & SEO",
    icon: Search,
    color: "indigo",
    packages: [
      {
        name: "Basic",
        price: "8.000.000đ",
        duration: "1 tháng",
        description: "Khởi động SEO cơ bản",
        features: [
          "Nghiên cứu từ khóa (20 từ)",
          "On-page SEO optimization",
          "Google My Business setup",
          "Tối ưu tốc độ website",
          "Báo cáo hàng tháng",
          "Google Analytics setup",
        ],
      },
      {
        name: "Premium",
        price: "18.000.000đ",
        duration: "3 tháng",
        description: "Lựa chọn phổ biến nhất",
        popular: true,
        features: [
          "Nghiên cứu từ khóa (50+ từ)",
          "On-page + Technical SEO",
          "Content marketing (4 bài/tháng)",
          "Link building chất lượng",
          "Google Ads setup & quản lý",
          "Social media marketing",
          "Báo cáo chi tiết 2 tuần/lần",
          "A/B testing campaigns",
        ],
      },
      {
        name: "Professional",
        price: "35.000.000đ +",
        duration: "6 tháng",
        description: "Chiến lược marketing toàn diện",
        features: [
          "Nghiên cứu thị trường chuyên sâu",
          "SEO strategy toàn diện",
          "Content marketing (12 bài/tháng)",
          "Link building cao cấp",
          "Google Ads + Facebook Ads",
          "Email marketing automation",
          "Influencer marketing",
          "CRO (Conversion Rate Optimization)",
          "Dedicated account manager",
          "Báo cáo tuần",
        ],
      },
    ],
  },
  software: {
    name: "Phát triển phần mềm",
    icon: Boxes,
    color: "emerald",
    packages: [
      {
        name: "Basic",
        price: "20.000.000đ",
        duration: "7-14 ngày",
        description: "Giải pháp phần mềm đơn giản",
        features: [
          "Phân tích yêu cầu cơ bản",
          "Phát triển chức năng cốt lõi",
          "Ứng dụng web đơn giản",
          "Responsive trên các thiết bị",
          "1 lần chỉnh sửa miễn phí",
        ],
      },
      {
        name: "Premium",
        price: "40.000.000đ",
        duration: "14-30 ngày",
        description: "Phần mềm theo yêu cầu doanh nghiệp",
        popular: true,
        features: [
          "Phân tích nghiệp vụ chi tiết",
          "Phát triển hệ thống theo quy trình doanh nghiệp",
          "Ứng dụng Web / Mobile",
          "Tích hợp API, thanh toán, quản lý dữ liệu",
          "Bảo mật & phân quyền người dùng",
          "2 lần chỉnh sửa miễn phí",
          "Hỗ trợ 30 ngày sau bàn giao",
        ],
      },
      {
        name: "Professional",
        price: "70.000.000đ +",
        duration: "30+ ngày",
        description: "Giải pháp phần mềm toàn diện",
        features: [
          "Thiết kế kiến trúc hệ thống chuyên sâu",
          "Phần mềm tùy chỉnh theo quy mô doanh nghiệp",
          "Tích hợp hệ thống nội bộ & bên thứ ba",
          "Hiệu năng cao, bảo mật nâng cao",
          "Analytics & báo cáo",
          "3 lần chỉnh sửa miễn phí",
          "Hỗ trợ & bảo trì 90 ngày",
        ],
      },
    ],
  },
}
